### PR TITLE
[WIP] Feat/cornerstone wado

### PR DESCRIPTION
**Pull request by sedghi**
Bringing [cornerstoneWADOImageLoader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader) to the cornerstonejs mono repo, why?

1. Convert the library to typescript 
2. Increasing need for webworkers in cornerstonejs, makes it hard to manage workers both in wado and here in core or tools or consuming apps (e.g., OHIF)
3. Better development experience for devs

Remaining works
- Adding the CSWIL examples
- Adding CSWIL tests

### CODE REVIEW

**Comment by jmannau** [comment]
Hi @sedghi I recently converted the cornerstoneWadoLoader to typescript myself and typed many of the functions.  Would you be interested in help with this? If so, do you have any thoughts/guidelines on how to name types? I normally prefix types used by a package with a common namespace ie: `CornerstoneWadoLoaderOptions` or `CornerstoneWadoLoaderImage extends IImage`.

**Comment by sedghi** [comment]
@jmannau This is awesome! and yes we are interested for sure.
How about you create a PR to this branch and we discuss there?

We always appreciate community support and give appropriate attributions as you can see in our previous newsletters [here](https://ohif.org/news/)

**Comment by jmannau** [comment]
I got started on this today. But ran into webpack config issues.  Is there somewhere to put chats/discussions. Rather than give myself more grey hair due to webpack - thought it best to ask if others have a suggestion

**Comment by sedghi** [comment]
closing in favor of https://github.com/cornerstonejs/cornerstone3D-beta/pull/343

**Pull request closed without merging**
