### PR TITLE
[WIP] initial commit for dicom image loader in mono repo

### PR DESCRIPTION
**Pull request by sedghi**
Initial draft PR

# Todo
@jmannau  
- I wasn't able to run the tests for the new dicom-image-loader. karma was complaining about ts file extension for tests, which I changed to .js but then after I got the following error. Have you verified that the tests run for dicom-image-loader?
image

### CODE REVIEW

**Comment by jmannau** [comment]
Hi @sedghi yes, I've been testing throughout my development. I have been running `yarn run test` in the root of the repo.  This runs all the tests for all projects.  

I just checked if it is a dependancy issue by removing node_modules and reinstalling, but that looks right to me.

I use MacOS & Node v18.  What environment are you using?

**Comment by sedghi** [comment]
@jmannau That is very odd, I just commented out the other packages tests in the karma, to see if it runs the WADO tests, and it didn't.

**Comment by jmannau** [comment]
I suspect the issue is that `karma.conf.js` is missing the required preprocessor for dicom-image-loader.  I don't know how/why it is working for me.  Can you try adding
```
      'packages/dicom-image-loader/test/**/*_test.js': ['webpack'],
```
to line 113?

**Comment by sedghi** [comment]
close in favor of the new dicomImageLoader in the main. @jmannau Now that we have the history for wado loader merged, can you please create your typed library PR to the main?

**Pull request closed without merging**
